<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */

return array (
  //'Please fix the following input errors:' =>'قم بتصحيح أخطاء المدخلات التالية :',
  //'Get a new code' => 'احصل على كود جديد',
    '{attribute} cannot be blank.' => 'Morate popuniti polje {attribute}.',
  );
