<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'الدخول ممنوع',
	'Add' => 'أضف',
	'Add child' => 'أضف ابن',
	'Add {type}' => 'أضف {type}',
	'Ancestors' => 'آباء',
	'Are you sure you want to delete this item?' => '؟ هل أنت متأكد أنك تلايد حذف هذا العنصر',
	'Assign' => 'إسناد',
	'Assign permission' => 'إسناد سماحية',
	'Assigned items' => 'إسناد عنصر',
	'Assignments' => 'المستخدمين',
	'Business rule' => 'قاعدة عمل',
	'Cancel' => 'إلغاء',
	'Create' => 'إنشاء',
	'Delete' => 'حذف',
	'Data' => 'بيانات',
	'Descendants' => 'الأبناء',
	'Description' => 'وصف',
	'Edit' => 'تعديل',
	'Invalid request.' => 'طلب خاطئ.',
	'Item does not exist.' => 'العنصر غير موجود',
	'Items' => 'عنصر',
	'Items assigned to this user' => 'العناصر المسندة إلى هذا المستخدم',
	'New {type}' => 'جديد {type}',
	'No assignments found.' => 'لايوجد اسنادات.',
	'No {type} found.' => 'لايوجد {type} .',
	'Page not found.' => 'الصفحة غير موجودة',
	'Permissions' => 'الصلاحيات',
	'Permissions granted by this item' => 'الصلاحيات الممنوحة من قبل هذا العنصر',
	'Permissions that inherit this item' => 'الصلاحيات التي يرثها هذا العنصر',
	'Remove' => 'إزالة',
	'Revoke' => 'إبطال',
	'Save' => 'حفظ',
	'Select item' => 'تحديد عنصر',
	'System name' => 'الاسم في النظام',
	'System name cannot be changed after creation.' => 'لا يمكن تعديل الاسم في النظام.',
	'This item does not have any ancestors.' => 'هذا العنصر لا يملك أي آباء.',
	'This item does not have any descendants.' => 'هذا العنصر لا يملك أي أبناء.',
	'This user does not have any assignments.' => 'هذا المستخدم لا يملك أي اسنادات.',
	'Type' => 'نوع',
	'User' => 'مستخدم',
	'View' => 'مشاهدة',
	'operation|operations' => 'عملية|العمليات',
	'role|roles' => 'قاعدة|القواعد',
    'task|tasks' => 'مهمة|المهمات',
    'roles' => 'القواعد',
    'tasks' => 'المهمات',
    'operations'=>'العمليات',
);
